[package]
name = "fator-semiprime"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "An implementation of the Pollard's rho algorithm for factoring semiprime numbers"

[dependencies]
rand = "0.8.5"
